<?php
require_once "../config/auth.php";
require_once "../config/database.php";
wajib_login(['wali_kelas']);

$uid=(int)($_SESSION['user_id']??0); $ok=''; $err='';
@mysqli_query($conn,"ALTER TABLE users ADD COLUMN profile_photo VARCHAR(255) DEFAULT NULL");
@mysqli_query($conn,"CREATE TABLE IF NOT EXISTS pengaturan (id INT AUTO_INCREMENT PRIMARY KEY,nama_kelas VARCHAR(100) NOT NULL DEFAULT 'XI TJKT 2',tahun_pelajaran VARCHAR(30) NOT NULL DEFAULT '2026 / 2027',nama_sekolah VARCHAR(150) NOT NULL DEFAULT 'SMK PGRI Subang',logo VARCHAR(255) DEFAULT NULL,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)");
@mysqli_query($conn,"INSERT INTO pengaturan (id) VALUES (1) ON DUPLICATE KEY UPDATE id=id");

$q=mysqli_prepare($conn,"SELECT nama,username,password,profile_photo FROM users WHERE id=? AND role='wali_kelas' LIMIT 1"); mysqli_stmt_bind_param($q,'i',$uid); mysqli_stmt_execute($q); mysqli_stmt_bind_result($q,$nama,$username,$hash,$photo); if(!mysqli_stmt_fetch($q)) die('Akun wali kelas tidak ditemukan.'); mysqli_stmt_close($q);
$r=mysqli_query($conn,"SELECT * FROM pengaturan WHERE id=1"); $cfg=mysqli_fetch_assoc($r)?:[];
$kelas=$cfg['nama_kelas']??'XI TJKT 2'; $tahun=$cfg['tahun_pelajaran']??'2026 / 2027'; $sekolah=$cfg['nama_sekolah']??'SMK PGRI Subang';
if(empty($_SESSION['csrf_settings'])) $_SESSION['csrf_settings']=bin2hex(random_bytes(32)); $csrf=$_SESSION['csrf_settings'];

if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!hash_equals($csrf,$_POST['csrf_token']??'')) $err='Permintaan tidak valid. Muat ulang halaman.';
 else {
  $action=$_POST['action']??'';
  if($action==='account'){
   $n=trim($_POST['nama']??''); $u=trim($_POST['username']??''); $old=$_POST['old_password']??''; $np=$_POST['new_password']??''; $cp=$_POST['confirm_password']??'';
   if($n===''||$u==='') $err='Nama dan username wajib diisi.'; elseif(strlen($u)<3||strlen($u)>50) $err='Username harus 3–50 karakter.'; elseif(!password_verify($old,$hash)) $err='Password lama salah.';
   else { $c=mysqli_prepare($conn,"SELECT id FROM users WHERE username=? AND id<>? LIMIT 1"); mysqli_stmt_bind_param($c,'si',$u,$uid); mysqli_stmt_execute($c); mysqli_stmt_store_result($c); $taken=mysqli_stmt_num_rows($c)>0; mysqli_stmt_close($c);
    if($taken) $err='Username tersebut sudah digunakan.'; elseif($np!==''&&strlen($np)<8) $err='Password baru minimal 8 karakter.'; elseif($np!==''&&$np!==$cp) $err='Konfirmasi password tidak cocok.';
    else { if($np!==''){ $nh=password_hash($np,PASSWORD_DEFAULT); $x=mysqli_prepare($conn,"UPDATE users SET nama=?,username=?,password=? WHERE id=?"); mysqli_stmt_bind_param($x,'sssi',$n,$u,$nh,$uid); } else { $x=mysqli_prepare($conn,"UPDATE users SET nama=?,username=? WHERE id=?"); mysqli_stmt_bind_param($x,'ssi',$n,$u,$uid); } if(mysqli_stmt_execute($x)){$_SESSION['nama']=$n;$_SESSION['username']=$u;$nama=$n;$username=$u;if($np!=='')$hash=$nh;$ok='Data akun berhasil diperbarui.';}else $err='Gagal memperbarui akun.'; mysqli_stmt_close($x); }
   }
  }
  if($action==='profile'){
   $n=trim($_POST['nama_profile']??''); $has=isset($_FILES['foto'])&&$_FILES['foto']['error']!==UPLOAD_ERR_NO_FILE;
   if($n==='') $err='Nama wali kelas wajib diisi.'; elseif(!$has){$x=mysqli_prepare($conn,"UPDATE users SET nama=? WHERE id=?");mysqli_stmt_bind_param($x,'si',$n,$uid);if(mysqli_stmt_execute($x)){$_SESSION['nama']=$n;$nama=$n;$ok='Profil wali kelas diperbarui.';}else $err='Gagal memperbarui profil.';mysqli_stmt_close($x);}
   elseif($_FILES['foto']['error']!==UPLOAD_ERR_OK) $err='Upload foto gagal.'; elseif($_FILES['foto']['size']>2097152) $err='Ukuran foto maksimal 2 MB.';
   else { $tmp=$_FILES['foto']['tmp_name']; $mime=function_exists('mime_content_type')?mime_content_type($tmp):''; $map=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp']; if(!isset($map[$mime]))$err='Format foto harus JPG, PNG, atau WEBP.'; else {$dir=__DIR__.'/../uploads/profile';if(!is_dir($dir))mkdir($dir,0755,true);$f='wali_'.$uid.'_'.bin2hex(random_bytes(6)).'.'.$map[$mime];$dest=$dir.'/'.$f;if(!move_uploaded_file($tmp,$dest))$err='Foto tidak dapat disimpan.';else{$x=mysqli_prepare($conn,"UPDATE users SET nama=?,profile_photo=? WHERE id=?");mysqli_stmt_bind_param($x,'ssi',$n,$f,$uid);if(mysqli_stmt_execute($x)){if($photo&&is_file($dir.'/'.$photo))@unlink($dir.'/'.$photo);$_SESSION['nama']=$n;$nama=$n;$photo=$f;$ok='Profil dan foto berhasil diperbarui.';}else{@unlink($dest);$err='Gagal memperbarui profil.';}mysqli_stmt_close($x);}}}
  }
  if($action==='class'){$kelas=trim($_POST['nama_kelas']??'');$tahun=trim($_POST['tahun_pelajaran']??'');$sekolah=trim($_POST['nama_sekolah']??'');if($kelas===''||$tahun===''||$sekolah==='')$err='Data kelas wajib diisi.';else{$x=mysqli_prepare($conn,"INSERT INTO pengaturan(id,nama_kelas,tahun_pelajaran,nama_sekolah) VALUES(1,?,?,?) ON DUPLICATE KEY UPDATE nama_kelas=VALUES(nama_kelas),tahun_pelajaran=VALUES(tahun_pelajaran),nama_sekolah=VALUES(nama_sekolah)");mysqli_stmt_bind_param($x,'sss',$kelas,$tahun,$sekolah);if(mysqli_stmt_execute($x))$ok='Pengaturan kelas berhasil disimpan.';else$err='Gagal menyimpan pengaturan kelas.';mysqli_stmt_close($x);}}
 }
}
$img=$photo?'../uploads/profile/'.rawurlencode($photo):'';
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pengaturan - XI TJKT 2</title><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"><style>*{box-sizing:border-box}body{margin:0;font-family:Arial,Helvetica,sans-serif;background:#f4f7fb;color:#172033}.page{max-width:1100px;margin:auto;padding:28px 20px 50px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:22px}.top h1{margin:0;font-size:28px}.top p{margin:6px 0;color:#64748b}.back{text-decoration:none;color:#334155;font-weight:700}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.card{background:#fff;border:1px solid #e8edf4;border-radius:18px;padding:22px;box-shadow:0 10px 30px rgba(15,23,42,.07)}.full{grid-column:1/-1}.card h2{font-size:18px;margin:0 0 5px}.desc{font-size:13px;color:#64748b;margin:0 0 18px}.field{margin-bottom:14px}.field label{display:block;font-size:13px;font-weight:700;margin-bottom:7px}.field input{width:100%;padding:12px;border:1px solid #d8dee8;border-radius:10px;font-size:14px}.btn{border:0;border-radius:10px;padding:11px 15px;background:#172033;color:#fff;font-weight:700}.alert{padding:12px 14px;border-radius:10px;margin-bottom:18px;background:#ecfdf5;color:#166534}.error{background:#fef2f2;color:#991b1b}.avatar,.avatar-empty{width:84px;height:84px;border-radius:50%;margin-bottom:12px}.avatar{object-fit:cover;border:3px solid #e5e7eb}.avatar-empty{background:#e8eef8;display:flex;align-items:center;justify-content:center;font-size:30px;color:#64748b}.note{font-size:12px;color:#64748b}@media(max-width:760px){.grid{grid-template-columns:1fr}.full{grid-column:auto}.top{align-items:flex-start}.top h1{font-size:23px}}
</style></head><body><div class="page"><div class="top"><div><h1><i class="fa-solid fa-gear"></i> Pengaturan</h1><p>Kelola akun wali kelas, profil, dan identitas kelas.</p></div><a class="back" href="index.php"><i class="fa-solid fa-arrow-left"></i> Dashboard</a></div>
<?php if($ok):?><div class="alert"><i class="fa-solid fa-circle-check"></i> <?=htmlspecialchars($ok)?></div><?php endif;?><?php if($err):?><div class="alert error"><i class="fa-solid fa-circle-exclamation"></i> <?=htmlspecialchars($err)?></div><?php endif;?>
<div class="grid"><section class="card"><h2><i class="fa-solid fa-shield-halved"></i> Akun & Keamanan</h2><p class="desc">Ganti username dan password login wali kelas.</p><form method="post"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($csrf)?>"><input type="hidden" name="action" value="account"><div class="field"><label>Nama akun</label><input name="nama" value="<?=htmlspecialchars($nama)?>" required></div><div class="field"><label>Username</label><input name="username" value="<?=htmlspecialchars($username)?>" required></div><div class="field"><label>Password lama</label><input type="password" name="old_password" required></div><div class="field"><label>Password baru <span style="font-weight:normal">(kosong = tetap)</span></label><input type="password" name="new_password" minlength="8"></div><div class="field"><label>Konfirmasi password baru</label><input type="password" name="confirm_password" minlength="8"></div><button class="btn">Simpan Akun</button></form></section>
<section class="card"><h2><i class="fa-solid fa-user-tie"></i> Profil Wali Kelas</h2><p class="desc">Foto profil akan tampil di dashboard.</p><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($csrf)?>"><input type="hidden" name="action" value="profile"><?php if($img):?><img class="avatar" src="<?=$img?>" alt="Foto wali kelas"><?php else:?><div class="avatar-empty"><i class="fa-solid fa-user-tie"></i></div><?php endif;?><div class="field"><label>Nama wali kelas</label><input name="nama_profile" value="<?=htmlspecialchars($nama)?>" required></div><div class="field"><label>Foto profil</label><input type="file" name="foto" accept="image/jpeg,image/png,image/webp"></div><div class="note">JPG, PNG, WEBP • maksimal 2 MB.</div><br><button class="btn">Simpan Profil</button></form></section>
<section class="card full"><h2><i class="fa-solid fa-school"></i> Identitas Kelas</h2><p class="desc">Data identitas yang ditampilkan pada sistem kelas.</p><form method="post"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($csrf)?>"><input type="hidden" name="action" value="class"><div class="grid"><div class="field"><label>Nama kelas</label><input name="nama_kelas" value="<?=htmlspecialchars($kelas)?>" required></div><div class="field"><label>Tahun pelajaran</label><input name="tahun_pelajaran" value="<?=htmlspecialchars($tahun)?>" required></div><div class="field"><label>Nama sekolah</label><input name="nama_sekolah" value="<?=htmlspecialchars($sekolah)?>" required></div></div><button class="btn">Simpan Identitas Kelas</button></form></section></div></div></body></html>
