<?php
require_once "../config/auth.php";
wajib_login(['siswa']);
$nama=$_SESSION['nama']??'Siswa';
?>
<!DOCTYPE html><html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Chat Kelas | XI TJKT 2</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"><style>
*{box-sizing:border-box}body{margin:0;background:#f4f7fb;color:#172033;font-family:Inter,"Segoe UI",Arial,sans-serif}.topbar{height:76px;background:#fff;border-bottom:1px solid #e8edf5;display:flex;align-items:center;padding:0 34px}.brand{display:flex;align-items:center;gap:13px}.brand-logo{width:45px;height:45px;border-radius:13px;object-fit:cover}.brand-title{font-size:17px;font-weight:800;margin:0}.brand-subtitle{font-size:12px;color:#8791a3}.page{max-width:900px;margin:auto;padding:30px 34px 50px}.back{color:#687386;text-decoration:none;font-size:13px;display:inline-block;margin-bottom:18px}.chat-card{background:#fff;border:1px solid #e8edf5;border-radius:20px;overflow:hidden}.chat-head{padding:19px 21px;border-bottom:1px solid #edf0f5}.chat-head h2{font-size:16px;margin:0;font-weight:800}.chat-head p{font-size:11px;color:#8791a3;margin:4px 0 0}.messages{height:500px;overflow-y:auto;padding:18px;background:#f8f9fc}.msg{margin-bottom:12px;max-width:80%}.msg.mine{margin-left:auto;text-align:right}.bubble{display:inline-block;background:#fff;border:1px solid #e5e9f0;border-radius:14px;padding:9px 12px;text-align:left;font-size:13px;white-space:pre-wrap;word-break:break-word}.mine .bubble{background:#172033;color:#fff;border-color:#172033}.meta{font-size:10px;color:#8993a4;margin:4px 3px}.send{padding:14px;border-top:1px solid #edf0f5;display:flex;gap:10px}.send input{flex:1;border:1px solid #dce2eb;border-radius:10px;padding:11px;outline:0}.send button{border:0;background:#172033;color:#fff;border-radius:10px;padding:0 17px}.empty{text-align:center;color:#8993a4;padding:50px 10px;font-size:13px}@media(max-width:600px){.topbar{padding:0 20px}.page{padding:20px}.messages{height:58vh}.msg{max-width:90%}}
</style></head><body><header class="topbar"><div class="brand"><img src="../assets/images/logo.png" class="brand-logo" alt="Logo"><div><p class="brand-title">XI TJKT 2</p><div class="brand-subtitle">Chat Kelas</div></div></div></header><main class="page"><a class="back" href="index.php"><i class="fa-solid fa-arrow-left"></i> Kembali ke Dashboard</a><div class="chat-card"><div class="chat-head"><h2><i class="fa-regular fa-comments"></i> Chat Kelas</h2><p>Tempat ngobrol bersama teman-teman sekelas.</p></div><div class="messages" id="messages"><div class="empty">Memuat chat...</div></div><form class="send" id="chatForm"><input id="pesan" name="pesan" maxlength="500" autocomplete="off" placeholder="Tulis pesan..." required><button type="submit"><i class="fa-solid fa-paper-plane"></i></button></form></div></main><script>
const box=document.getElementById('messages'),form=document.getElementById('chatForm'),input=document.getElementById('pesan');
async function loadChat(){try{const r=await fetch('chat_api.php?limit=50',{cache:'no-store'});const d=await r.json();if(!d.ok)throw Error();if(!d.messages.length){box.innerHTML='<div class="empty">Belum ada chat. Jadilah yang pertama mengirim pesan.</div>';return;}const nearBottom=box.scrollHeight-box.scrollTop-box.clientHeight<80;box.innerHTML=d.messages.map(m=>`<div class="msg ${m.user_id==<?= (int)($_SESSION['user_id']??0) ?>?'mine':''}"><div class="meta">${escapeHtml(m.nama_pengirim)} · ${m.waktu}</div><div class="bubble">${escapeHtml(m.pesan)}</div></div>`).join('');if(nearBottom)box.scrollTop=box.scrollHeight;}catch(e){}}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
form.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form);const r=await fetch('chat_api.php',{method:'POST',body:fd});const d=await r.json();if(d.ok){input.value='';await loadChat();box.scrollTop=box.scrollHeight;}else alert(d.message||'Gagal mengirim pesan.');});loadChat();setInterval(loadChat,3000);
</script></body></html>
